apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\dtanimoto.SHINWART\Desktop\wp\kompose-windows-amd64.exe
      convert -f .\docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\dtanimoto.SHINWART\Desktop\wp\kompose-windows-amd64.exe
          convert -f .\docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: db:3306
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: volumes
          value: db_data
        image: wordpress:latest
        imagePullPolicy: ""
        name: wordpress
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/wp-content
          name: wordpress-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: wordpress-claim0
        persistentVolumeClaim:
          claimName: wordpress-claim0
status: {}
