apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\dtanimoto.SHINWART\Desktop\wp\kompose-windows-amd64.exe
      convert -f .\docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: wordpress
status:
  loadBalancer: {}
