jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - kube-orb/install-kubectl
      - kube-orb/install-kubeconfig:
          kubeconfig: SPORT_KUBECONFIG
orbs:
  kube-orb: circleci/kubernetes@1.0.0
version: 2.1
