version: 2.1
executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - kube-orb/install-kubectl
      - kube-orb/install-kubeconfig:
          kubeconfig: SPORT_KUBECONFIG
      - kube-orb/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: case2/sample-deployment.yaml
          resource-name: deployment/sample-deployment
          show-kubectl-command: true
      - run:
          command: |
            kubectl apply -f case2/sample-lb-service.yaml
orbs:
  kube-orb: circleci/kubernetes@0.11.1
