jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - kube-orb/install-kubectl
      - kube-orb/install-kubeconfig:
          kubeconfig: SPORT_KUBECONFIG
orbs:
  kube-orb: circleci/kubernetes@0.11.1
version: 2.1
