version: 2.1
executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - kube-orb/install-kubectl
      - kube-orb/install-kubeconfig:
          kubeconfig: SPORT_KUBECONFIG
      - run:
          command: |
            cd case2
            CIP=$(kubectl get svc | grep mysql | awk '{print $3 }')
            cd wordpress
            sed -i -e "s/SVCCIP/$CIP/g" wordpress.yaml
            cat mysql-service.yaml
orbs:
  kube-orb: circleci/kubernetes@0.11.1
