version: 2.1
executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - kube-orb/install-kubectl
      - kube-orb/install-kubeconfig:
          kubeconfig: SPORT_KUBECONFIG
      - run:
          command: |
            cd case2
            kubectl get svc | grep mysql | awk '{print $3 | getline CIP}'
            echo $CIP
orbs:
  kube-orb: circleci/kubernetes@0.11.1
