version: 2.1
executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"

jobs:
  checkout:
    executor: my-executor
    steps:
      - checkout

  kubectl-setting:
    executor: my-executor
    steps:
      - kube-orb/install-kubectl
      - kube-orb/install-kubeconfig:
          kubeconfig: SPORT_KUBECONFIG
orbs:
  kube-orb: circleci/kubernetes@0.11.1

workflows:
  version: 2.1
  build_and_setting:
    jobs:
      - checkout
      - kubectl-setting:
        requires:
          - checkout
