version: 2.1
executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - kube-orb/install-kubectl
      - kube-orb/install-kubeconfig:
          kubeconfig: SPORT_KUBECONFIG
      - run:
          command: |
            curl -L https://github.com/kubernetes/kompose/releases/download/v1.21.0/kompose-linux-amd64 -o kompose
            chmod +x kompose
            sudo mv ./kompose /usr/local/bin/kompose
            cd case2
            kompose convert -f docker-compose.yaml
            kompose up -f docker-compose.yaml
orbs:
  kube-orb: circleci/kubernetes@0.11.1
