apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - image: dtanimoto/stg-test-k8s:latest
          name: nodejs-app
          ports:
            - containerPort: 3000
              name: nodejs-app
