apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 218.223.86.176
    path: /export/nfs/wordpress
