apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-sample
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    app: sample-app
  externalIPs:
    - 218.223.86.177
