apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
  externalIPs:
    - 218.223.86.177
